"""initial schema

Revision ID: b39174580f81
Revises: 
Create Date: 2026-07-01 20:01:27.674292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39174580f81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_logs_command'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_created_at'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_user_id'), table_name='command_logs')
    op.drop_table('command_logs')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=1)
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=30), nullable=False),
    sa.Column('shares', sa.INTEGER(), nullable=False),
    sa.Column('avg_price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol')
    )
    op.create_table('command_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('command', sa.VARCHAR(length=50), nullable=False),
    sa.Column('args', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_logs_user_id'), 'command_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_command_logs_created_at'), 'command_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_command_logs_command'), 'command_logs', ['command'], unique=False)
    # ### end Alembic commands ###
